server:
  port: 8902
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  application:
    name: Notificaton-service
  cloud:
    zookeeper:
      discovery:
        enabled: true
        connect-string: localhost:2181
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

producer:
  kafka:
    topic-name: testTopic
